name: Integration tests for application

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests-arm:
    name: Integration test (ARM64)
    runs-on: [self-hosted, ARM64, jammy, stg-private-endpoint]
    strategy:
      fail-fast: false
      matrix:
        image: [noble]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: canonical/setup-lxd@v0.1.2
      - name: Install tox
        run: |
          sudo apt-get update
          sudo apt-get install pipx -y
          pipx ensurepath
          pipx install tox
      - name: Run integration tests
        env:
          OPENSTACK_PASSWORD_ARM64: ${{ secrets.OPENSTACK_PASSWORD_ARM64 }}
        run: |
         cd app
         tox -e integration -- -m arm64 --image=${{ matrix.image }} ${{ secrets.INTEGRATION_TEST_ARGS_APP }}
  integration-tests-amd:
    name: Integration test (X64)
    runs-on: [self-hosted, X64, jammy, stg-private-endpoint]
    strategy:
      fail-fast: false
      matrix:
        image: [jammy, noble]
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: canonical/setup-lxd@v0.1.2
      - name: Install tox
        run: |
          sudo apt-get update
          sudo apt-get install pipx -y
          pipx ensurepath
          pipx install tox
      - name: Run integration tests
        env:
          OPENSTACK_PASSWORD_AMD64: ${{ secrets.OPENSTACK_PASSWORD_AMD64 }}
        run: |
         cd app 
         tox -e integration -- -m amd64 --image=${{ matrix.image }} ${{ secrets.INTEGRATION_TEST_ARGS_APP }}
  required_status_checks:
    name: Required Integration Test For Application Status Checks
    runs-on: ubuntu-latest
    needs:
      - integration-tests-amd
      - integration-tests-arm
    if: always() && !cancelled()
    timeout-minutes: 5
    steps:
      - run: |
          [ '${{ needs.integration-tests-amd.result }}' = 'success' ] || (echo integration-tests-amd failed && false)
          [ '${{ needs.integration-tests-arm.result }}' = 'success' ] || (echo integration-tests-arm failed && false)
