name: Tests for application

on:
  pull_request:

jobs:
  unit-tests-for-app:
    uses: canonical/operator-workflows/.github/workflows/test.yaml@main
    secrets: inherit
    with:
      python-version: "3.10"
      self-hosted-runner: true
      working-directory: ./app/
