name: CI
on: [push]
jobs:
  build:
    runs-on: [self-hosted, linux, self-hosted-linux-amd64-jammy-large]
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: canonical/action-tmate@main